---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <DEPLOYMENT_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      name: <LABEL_NAME>
  template:
    metadata:
      labels:
        name: <LABEL_NAME>
    spec:
      containers:
      - name: <CONTAINER_NAME>
        image: <IMAGE_NAME:TAG>
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "1"
        #restartPolicy: OnFailure
        ports:
          - containerPort: 9005
