---
apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
spec:
  type: LoadBalancer
  #type: NodePort
  #externalIPs:
          #- 3.12.142.195
  ports:
  - name: http
    port: 80
    targetPort: 9005
    #nodePort: 30935
  selector:
    name: rest-api
